# Generated by Django 4.1.2 on 2022-10-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/profileCard/')),
                ('designation', models.CharField(max_length=2000)),
                ('company', models.CharField(max_length=2000)),
            ],
        ),
    ]
