# Generated by Django 4.1.2 on 2022-10-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=2000)),
                ('institute', models.CharField(max_length=2000)),
                ('awardingBody', models.CharField(max_length=2000)),
                ('passingYear', models.DateField()),
            ],
        ),
    ]
