# Generated by Django 4.1.2 on 2022-10-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='passingYear',
            field=models.IntegerField(),
        ),
    ]
