# Generated by Django 3.2.13 on 2022-10-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000)),
                ('description', models.TextField(max_length=99999)),
                ('image', models.ImageField(upload_to='static/bio/')),
            ],
        ),
    ]
