# Generated by Django 4.1.2 on 2022-10-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='static/content/')),
                ('link', models.URLField(max_length=20000)),
            ],
        ),
    ]
