# Generated by Django 4.1.2 on 2022-10-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
