# Generated by Django 4.1.2 on 2022-10-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
